<main class="min-h-screen grid gap-2 justify-center content-center">
    <span class="landing_title md:text-6xl">Vai rolar festinha?</span>
    <span class="landing_title md:text-6xl">Chama no Buff<a>Eats</a>!</span>
    <span class="landing_subtitle md:text-2xl m-1">Com a BuffEats você pode escolher buffets<br>de qualidade e com
        preços
        justos.</span>

        <button class="btn btn-accent btn-outline w-1/1 md:w-1/2 justify-self-center">Button</button>

    <a href="#" class="btn-red text-center w-1/1 md:w-1/2 justify-self-center">
        Tenho interesse!
    </a>
</main>