<main class="min-h-screen">
    <div class="cardContainer">
        <form method="post" action="">
            <div class="grid gap-2 content-center justify-center">
                <h1 class="text-4xl text-center">Login</h1>

                <label class="">Email:</label>
                <input type="text" name="email" id="username" class="input input-bordered w-full max-w-xs">

                <label class="login_subtitle">Senha:</label>
                <input type="password" name="password" id="password" class="input_box">

                <button type="submit" name="submit" class="button_submit">ENTRAR</button>

                <label class="login_inscrever"><a href="../Decisao/decisao.php" class="none_inscrever">Não tem uma
                        conta?
                        <B>Inscreva-se!</B></a></label>
                <div id="container_gmail">
                    <!-- <img src="img/Icon_Google.svg" width="25px">
                    <label class="login_gmail">LOGAR COM O GMAIL</label> -->
                </div>
                <div id="container_termos">
                    <label class="login_termos"><a href="../Privacidade/index.php" class="none_termos">Termos de
                            privacidade</a></label>
                </div>
        </form>
    </div>
    </div>
</main>
</body>

</html>