<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <script src="./js/animations.js" defer></script>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="./img/favicon.png">
    <title>BuffEats - Home</title>
</head>

<body class="bg-cinzafundo">

    <?php include_once('Headers/headerSemLogin.phtml'); ?>

    <?= $this->content() ?>
</body>

</html>